[metadata]
name = sasci360solworkflow
version = 0.0.1
author = Mark Nelson
author_email = Mark.Nelson@sas.com
description = An awesome package that does something
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.sas.com/psd-ci-enablement/sas_ci360_sol_workflow
project_urls = Bug Tracker = https://gitlab.sas.com/psd-ci-enablement/sas_ci360_sol_workflow/issues
classifiers = Programming Language :: Python :: 3
	License :: OSI Approved :: MIT License
	Operating System :: OS Independent

[install_requires]
package = pandas~=1.4.2
	PyJWT~=2.3.0
	requests~=2.27.1
	saspy~=4.2.0
	schedule~=1.1.0
	DateTime~=4.3
	sasci360solworkflow~=0.0.1
	sasci360apiworkflow~=0.0.1
	sasci360apicore~=0.0.1
	urllib3~=1.26.9

[options]
package_dir = = src
packages = find:
python_requires = >=3.6

[options.packages.find]
where = src
